# Generated by Django 4.2.6 on 2024-07-19 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_news_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категория'},
        ),
    ]
