# Generated by Django 4.2.6 on 2024-07-21 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_category_options_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date', 'id', 'time_create', 'title'], 'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
    ]
