# Generated by Django 4.2.6 on 2024-10-06 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_telegramsubscriber_news_is_sent_alter_news_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='В соцсети'),
        ),
    ]
