# Generated by Django 4.2.6 on 2024-10-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_news_is_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=255, unique=True, verbose_name='Название валюты')),
                ('currency_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата курса')),
                ('currency_rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс валюты')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['currency_name'],
            },
        ),
        migrations.AddField(
            model_name='telegramsubscriber',
            name='frequency_sending',
            field=models.CharField(choices=[('every_hour', 'Каждый час'), ('every_3hour', 'Каждые 3 часа'), ('every_6hour', 'Каждые 6 часов'), ('every_9hour', 'Каждые 9 часов'), ('every_12hour', 'Каждые 12 часов'), ('daily', 'Ежедневно')], default='every_hour', verbose_name='Частота рассылки'),
        ),
        migrations.AddField(
            model_name='telegramsubscriber',
            name='message_format',
            field=models.CharField(choices=[('full', 'Полные сообщения'), ('short', 'Сокращенные сообщения')], default='short', verbose_name='Формат сообщений'),
        ),
        migrations.AddField(
            model_name='telegramsubscriber',
            name='subscribed_to_categories',
            field=models.ManyToManyField(blank=True, to='news.category', verbose_name='Подписка на категориии новостей'),
        ),
        migrations.AddField(
            model_name='telegramsubscriber',
            name='subscribed_weather_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подписка на прогноз погоды по городу'),
        ),
        migrations.AddField(
            model_name='telegramsubscriber',
            name='subscribed_to_currency',
            field=models.ManyToManyField(blank=True, to='news.currency', verbose_name='Подписка на валюты'),
        ),
    ]
