# Generated by Django 4.2.6 on 2024-10-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_telegramsubscriber_currency_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramsubscriber',
            name='subscribed_to_categories',
            field=models.ManyToManyField(blank=True, to='news.category', verbose_name='Категориии новостей'),
        ),
    ]
