# Generated by Django 4.2.6 on 2024-10-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_alter_telegramsubscriber_subscribed_to_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramsubscriber',
            name='subscribed_weather_city',
        ),
        migrations.AddField(
            model_name='telegramsubscriber',
            name='subscribed_weather_city',
            field=models.ManyToManyField(blank=True, to='news.city', verbose_name='Города для прогноза'),
        ),
    ]
