# Generated by Django 4.2.6 on 2024-10-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_remove_telegramsubscriber_subscribed_weather_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency_name',
            field=models.CharField(max_length=255, verbose_name='Название валюты'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Символ валюты'),
        ),
    ]
