# Generated by Django 4.2.6 on 2024-11-02 19:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_alter_currencyrate_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата отправки')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news', verbose_name='Новости')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.telegramsubscriber', verbose_name='Подписчик')),
            ],
            options={
                'verbose_name': 'Отпарвленная новость',
                'verbose_name_plural': 'Отправленные новости',
                'unique_together': {('subscriber', 'news')},
            },
        ),
    ]
